DBCC FREEPROCCACHE
DBCC DROPCLEANBUFFERS
 ALTER DATABASE jmjuradotestdb1 SET QUERY_STORE CLEAR;
 ALTER DATABASE jmjuradotestdb2 SET QUERY_STORE CLEAR;
 ALTER DATABASE jmjuradotestdb3 SET QUERY_STORE CLEAR;
